services:
  crow-backend:
    build:
      context: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - PORT=8000
      - BUILD_TYPE=Release
      - GOOGLE_API_KEY=AIzaSyB9Gv3QO1XNNa4zdQI3Ynj8pfwt6Qn_D-w
    
