/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car1.gltf 
Author: arturs.vitas (https://sketchfab.com/arturs.vitas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cartoon-style-car-03-8c7f36b0a60745f487b300fa74d05990
Title: Low-poly cartoon style car 03
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Car1/car1.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={[2,2,2]}ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Wheel_FL_0" position={[0.45, 0.141, 0.603]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Wheel_FR_1" position={[-0.449, 0.141, 0.603]}>
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Wheel_RL_2" position={[0.449, 0.134, -0.474]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Wheel_RR_3" position={[-0.444, 0.147, -0.453]}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Body_10" position={[0, 0.165, -0.002]}>
                <group name="Assymetry_4" position={[0.002, -0.066, 0.117]}>
                  <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.BodyMatte} />
                </group>
                <group name="Engine_T2_5" position={[0, -0.043, 0.52]}>
                  <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.BodyMatte} />
                </group>
                <group name="InteriorAssymetry_6" position={[0.256, 0.233, 0.296]}>
                  <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.BodyMatte} />
                </group>
                <group name="Suspension_RL_7" position={[0.325, 0.192, -0.452]} rotation={[0.038, -0.01, 0.063]}>
                  <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.BodyMatte} />
                </group>
                <group name="Suspension_RR_8" position={[-0.325, 0.192, -0.452]} rotation={[0.038, -0.015, -0.062]}>
                  <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.BodyMatte} />
                </group>
                <group name="WindshieldWipers_9" position={[0.01, 0.282, 0.485]}>
                  <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.BodyMatte} />
                </group>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.BodyMatte} />
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.BodyGlass} />
              </group>
              <group name="Suspension_FR_11" position={[-0.308, 0.345, 0.572]} rotation={[-0.138, 0.01, -0.063]} scale={[1, 0.81, 1]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Suspension_FL_12" position={[0.308, 0.345, 0.572]} rotation={[-0.134, -0.01, 0.062]} scale={[1, 0.81, 1]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Axle_FR_13" position={[0, 0.14, 0.603]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Axle_FL_14" position={[0, 0.14, 0.603]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Bonet_15" position={[0, 0.425, 0.463]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Axle_RL_16" position={[0.311, 0.129, -0.209]}>
                <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Doors_R_17" position={[-0.485, 0.256, 0.43]}>
                <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.BodyMatte} />
                <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.BodyGlass} />
              </group>
              <group name="Lights_RL_18" position={[0.322, 0.294, -0.667]}>
                <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.BodyMatte} />
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.BodyEmission} />
              </group>
              <group name="Bootlid_20" position={[0, 0.821, -0.374]}>
                <group name="Assymetry_1_19" position={[-0.291, -0.462, -0.313]}>
                  <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.BodyGlossy} />
                </group>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.BodyMatte} />
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.BodyGlass} />
              </group>
              <group name="Bumper_R_21" position={[0, 0.195, -0.713]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Fender_FR_22" position={[-0.469, 0.303, 0.553]}>
                <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Lights_RR_23" position={[-0.325, 0.295, -0.666]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.BodyMatte} />
                <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.BodyEmission} />
              </group>
              <group name="Axle_RR_24" position={[-0.311, 0.142, -0.188]}>
                <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Doors_L_25" position={[0.485, 0.256, 0.43]}>
                <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.BodyMatte} />
                <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.BodyGlass} />
              </group>
              <group name="Fender_FL_26" position={[0.469, 0.303, 0.553]}>
                <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Bumper_F_27" position={[0, 0.147, 0.853]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.BodyMatte} />
              </group>
              <group name="Headlight_FR_28" position={[-0.332, 0.281, 0.804]}>
                <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.BodyMatte} />
                <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.BodyEmission} />
              </group>
              <group name="TurnSignal_FR_29" position={[-0.441, 0.276, 0.785]}>
                <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.BodyMatte} />
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.BodyEmission} />
              </group>
              <group name="Headlight_FL_30" position={[0.332, 0.281, 0.804]}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.BodyGlossy} />
                <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.BodyMatte} />
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.BodyEmission} />
              </group>
              <group name="TurnSignal_FL_31" position={[0.441, 0.276, 0.785]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.BodyMatte} />
                <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.BodyEmission} />
              </group>
              <group name="Fan_32" position={[0.002, 0.168, 0.737]}>
                <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.BodyMatte} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car1.gltf')
