/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 man.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/People/Man/man.gltf')
  return (
    <group scale={[0.028, 0.02,0.02]}{...props} dispose={null}>
      <mesh geometry={nodes.ManDefault.geometry} material={materials.default2} position={[2.835, 0, -51.863]} rotation={[0, -0.02, -0.007]} />
      <mesh geometry={nodes.ManHair.geometry} material={materials.Hair1} position={[2.835, 0, -51.863]} rotation={[0, -0.02, -0.007]} />
      <mesh geometry={nodes.ManPantsPhone.geometry} material={materials.Wear_4} position={[2.835, 0, -51.863]} rotation={[0, -0.02, -0.007]} />
      <mesh geometry={nodes.ManShirt.geometry} material={materials.Wear1} position={[2.835, 0, -51.863]} rotation={[0, -0.02, -0.007]} />
      <mesh geometry={nodes.ManShoes.geometry} material={materials.Wear_3} position={[2.835, 0, -51.863]} rotation={[0, -0.02, -0.007]} />
      <mesh geometry={nodes.ManSkin.geometry} material={materials.Skin1} position={[2.835, 0, -51.863]} rotation={[0, -0.02, -0.007]} />
    </group>
  )
}

useGLTF.preload('/man.gltf')
