/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 people.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/People/people.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_Floor1_0.geometry} material={materials.Floor1} />
      <mesh geometry={nodes.Mesh_Hair1_0.geometry} material={materials.Hair1} />
      <mesh geometry={nodes.Mesh_Wear1_0.geometry} material={materials.Wear1} />
      <mesh geometry={nodes.Mesh_Wear_3_0.geometry} material={materials.Wear_3} />
      <mesh geometry={nodes.Mesh_Skin1_0.geometry} material={materials.Skin1} />
      <mesh geometry={nodes.Mesh_Wear_4_0.geometry} material={materials.Wear_4} />
      <mesh geometry={nodes.Mesh_default2_0.geometry} material={materials.default2} />
      <mesh geometry={nodes.Mesh_Wear_6_0.geometry} material={materials.Wear_6} />
    </group>
  )
}

useGLTF.preload('/People/people.gltf')
